# Generated by Django 4.1.5 on 2023-03-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indianspots',
            name='desc',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
