# Generated by Django 4.1.5 on 2023-03-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_indianspots_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foreignspots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.TextField(max_length=20)),
                ('days', models.IntegerField()),
                ('desc', models.TextField(default=None, max_length=200)),
            ],
        ),
    ]
