# Generated by Django 4.1.5 on 2023-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_foreignspots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('price', models.TextField(max_length=20)),
                ('days', models.IntegerField()),
            ],
        ),
    ]
